apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: keycloak-jwt-validator
  namespace: istio-ingress
spec:
  selector:
    matchLabels:
      istio: main-gateway
  jwtRules:
  - issuer: "https://seu-keycloak.com/realms/seu-realm"
    jwksUri: "https://seu-keycloak.com/realms/seu-realm/protocol/openid-connect/certs"
