apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: keycloak-jwt-validator
  namespace: istio-ingress
spec:
  targetRef:
    kind: Gateway
    group: gateway.networking.k8s.io
    name: main-gateway
  jwtRules:
  - issuer: "https://auth-dev.modernatec.com.br/realms/poc-realm"
    jwksUri: "https://auth-dev.modernatec.com.br/realms/poc-realm/protocol/openid-connect/certs"
    forwardOriginalToken: true