apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: certtest-virtual-service
  namespace: default
spec:
  hosts:
  - "demo.modernatec.com.br"
  gateways:
  - istio-ingress/main-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: modernatec
        port:
          number: 8080