apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-ingress 
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "demo.modernatec.com.br"
    #tls:
    #  httpsRedirect: true

  #- port:
  #    number: 443
  #    name: https
  #    protocol: HTTPS
  #  hosts:
  #  - "demo.modernatec.com.br"
  #  tls:
  #    mode: SIMPLE
  #    credentialName: moderna-credential