apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: istio-ingress
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "15021"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-path: "/healthz/ready"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "http"
spec:
  gatewayClassName: istio
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    hostnames:
      - "demo.mycompany.com.br"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: moderna-credential